coverage:
  status:
    project: # Measures overall project coverage.
      default:
        target: auto
        threshold: 1%
        informational: true # Project coverage for stats only.
    patch: #  Only measures lines adjusted in the pull request.
      default:
        target: auto
        threshold: 5%
        informational: false # true: Patch coverage for stats only.