"""Tests for Identity data structure."""

from __future__ import annotations

import pytest

from sleap_io.model.identity import Identity


def test_identity_defaults():
    """Test Identity construction with defaults."""
    identity = Identity()
    assert identity.name == ""
    assert identity.color is None
    assert identity.metadata == {}


def test_identity_full():
    """Test Identity construction with all fields."""
    identity = Identity(name="mouse_A", color="#ff0000", metadata={"weight": 25.0})
    assert identity.name == "mouse_A"
    assert identity.color == "#ff0000"
    assert identity.metadata == {"weight": 25.0}


def test_identity_eq_false():
    """Test that Identity uses object identity for equality (eq=False)."""
    id1 = Identity(name="mouse_A")
    id2 = Identity(name="mouse_A")
    assert id1 is not id2
    assert id1 != id2  # eq=False means different objects are not equal


def test_identity_repr():
    """Test Identity string representation surfaces name, truncated uuid, color."""
    id1 = Identity(name="mouse_A", uuid="0123456789abcdef0123456789abcdef")
    assert repr(id1) == 'Identity(name="mouse_A", uuid="01234567…")'

    id2 = Identity(
        name="mouse_A", uuid="0123456789abcdef0123456789abcdef", color="#ff0000"
    )
    assert repr(id2) == 'Identity(name="mouse_A", uuid="01234567…", color="#ff0000")'

    # Two identities differing only by uuid no longer repr identically.
    assert repr(Identity(name="x")) != repr(Identity(name="x"))


def test_identity_hashable():
    """Test that Identity objects can be used in sets and as dict keys."""
    id1 = Identity(name="a")
    id2 = Identity(name="b")
    s = {id1, id2}
    assert len(s) == 2
    d = {id1: "first", id2: "second"}
    assert d[id1] == "first"


def test_identity_uuid_autogenerated():
    """Test that each Identity gets a unique 32-char hex uuid by default."""
    id1 = Identity(name="mouse_A")
    id2 = Identity(name="mouse_A")
    assert isinstance(id1.uuid, str)
    assert len(id1.uuid) == 32
    int(id1.uuid, 16)  # valid hex
    assert id1.uuid != id2.uuid  # distinct objects get distinct uuids


def test_identity_uuid_explicit():
    """Test that an explicit uuid is preserved."""
    identity = Identity(name="mouse_A", uuid="abc123")
    assert identity.uuid == "abc123"


def test_identity_uuid_stable():
    """Test that the uuid does not change across reads."""
    identity = Identity(name="mouse_A")
    first = identity.uuid
    assert identity.uuid == first


def test_identity_matches_uuid():
    """Test matching by the stable uuid key (the default)."""
    id1 = Identity(name="mouse_A", uuid="shared")
    id2 = Identity(name="different", uuid="shared")  # same uuid, different name
    id3 = Identity(name="mouse_A")  # same name, different uuid
    assert id1.matches(id2)  # default method is uuid
    assert id1.matches(id2, method="uuid")
    assert not id1.matches(id3, method="uuid")


def test_identity_matches_name():
    """Test matching by name."""
    id1 = Identity(name="mouse_A")
    id2 = Identity(name="mouse_A")  # different uuid, same name
    id3 = Identity(name="mouse_B")
    assert id1.matches(id2, method="name")
    assert not id1.matches(id3, method="name")


def test_identity_matches_object_identity():
    """Test matching by Python object identity."""
    id1 = Identity(name="mouse_A", uuid="shared")
    id2 = Identity(name="mouse_A", uuid="shared")  # same fields, different object
    assert id1.matches(id1, method="identity")
    assert not id1.matches(id2, method="identity")


def test_identity_matches_invalid_method():
    """Test that an unknown matching method raises ValueError."""
    id1 = Identity(name="mouse_A")
    id2 = Identity(name="mouse_A")
    with pytest.raises(ValueError, match="Unknown matching method"):
        id1.matches(id2, method="bogus")
