# Package builds
name: Build

on:
  release:
    types:
      - published
  # # Modify and uncomment below to manually trigger build:
  # push:
  #   branches:
  #     - talmo/v0.0.7

jobs:
  pypi:
    name: PyPI Wheel
    runs-on: "ubuntu-22.04"
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --editable .[dev]

    - name: Build wheel
      run: |
        python -m build --wheel --sdist
        twine check dist/*
    
    - name: Upload
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload -u __token__ -p "$PYPI_TOKEN" dist/* --non-interactive --skip-existing --disable-progress-bar
