# Linting with Black
name: Lint

on:
  push:
    paths:
      - "sleap_io/**"
      - "tests/**"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-22.04"
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3.0.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --editable .[dev]

    - name: Run Black
      run: |
        black --check sleap_io tests
    
    - name: Run pydocstyle
      run: |
        pydocstyle --convention=google sleap_io/