# Static type checking with MyPy
#
# Note: We check using Python 3.9 to use the newer conventions for generic types.
#
# For a workaround on previous versions, simply add this import:
#   from __future__ import annotations
#
# See: https://mypy.readthedocs.io/en/stable/builtin_types.html#generic-types
name: Type checks

on:
  push:
    paths:
      - "sleap_io/**"
      - ".github/workflows/type_checks.yml"

jobs:
  type_checks:
    name: Type checks
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install mypy
          pip install types-attrs
          pip install attrs>=21.2.0

      - name: Run MyPy
        run: |
          mypy --follow-imports=skip --ignore-missing-imports sleap_io tests
